name: Generate Docs
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Install Python
        uses: actions/setup-python@5.1.1
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade-pip
          pip install pyyaml
      - name: Run docs generator
        run: python generate-docs.py
      - name: Push newly generated doc
        run: |
          git config user.name github-actions
          git config user.email github-actions@gmail.com
          git add -A
          git commit -m 'Action - Generated Docs'
          git push
